version: '3'

services:
  mysql:
    container_name: greibit-menu-manager-mysql
    image: mysql:8.0
    ports:
      - 3399:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  menu_manager_api:
    container_name: greibit-menu-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8099:8000"
      - "9099:9000"
    volumes:
      - .:/app
    command: symfony serve --dir=public --port=8000 --force-php-discovery